### PR TITLE
Use setuptools declarative syntax via setup.cfg

### PR DESCRIPTION
**Pull request by jdufresne**
https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html

This avoids mixing code and configuration, reduces boilerplate, and
avoids custom logic at installation time.

### CODE REVIEW

**Comment by jdufresne** [comment]
Fixed merge conflicts

**Comment by boxed** [comment]
This looks nice! There's a merge conflict though, but I guess that's actually trivial to resolve?

**Comment by jdufresne** [comment]
Rebased and resolved conflict.

**Comment by boxed** [comment]
Thanks!

**Pull request merged**
