### PR TITLE
#142 Added AutoStepTimeFactory

### PR DESCRIPTION
**Pull request by sheepsy90**
Saw the feature request - needed it myself - implemented it - only drawback is the conflict with the tick parameter as there are now 3 different factories. Maybe a refactoring necessary to support multiple of those factories on init. That would also support generators being passed to have custom steps in time.

### CODE REVIEW

**Comment by sheepsy90** [comment]
@spulec What about this pull request - i kind of need the functionality i added a lot - might be useful for others as well

**Comment by spulec** [comment]
Thanks for this.

If you resolve conflicts and undo the version change, I'll be happy to merge

**Comment by languitar** [comment]
Any chance to get this rolling again?

**Comment by boxed** [comment]
The CI build seems to fail because python 3.3 isn't available on travis? Seems like a safe thing to ignore that and merge this?

**Comment by spulec** [comment]
Thanks!

**Pull request merged**
