### PR TITLE
[compat] Drop support of py27

### PR DESCRIPTION
**Pull request by Djailla**
Python 2.7 is deprecated
Drop support and remove six dependency

### CODE REVIEW

**Comment by boxed** [comment]
Hell yes! I think we can be ok with people who need py2 having to use an older version. 

Agreed @spulec ?

**Comment by Djailla** [comment]
Hello @boxed / @spulec any update for this PR ?

**Comment by Djailla** [comment]
Hello @boxed 

Shall I spend some time rebasing this commit ?

**Comment by boxed** [comment]
Yes please. I will merge this if you do.

**Comment by Djailla** [comment]
@boxed the CI fails for pypy3 but related to pendulum

**Comment by boxed** [comment]
Hmmm, yea the master branch is failing with the same error.

**Pull request merged**
