### PR TITLE
Typeshed types

### LINKED ISSUE #318: Add mypy types (or type stubs)
Hi,

my colleague(s) and I are currently working on writing (a subset of) type stubs for freezegun and we were wondering if it would make sense to contribute them.

Going by the [contribution guide for typeshed](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library) the first step in the process is asking the maintainers of the libraries if they want to integrate the type hints into the library directly.
What is your opinion on this?

Contributing the types here could be done one of the following ways:

- adding the types as separate stub files
- adding the types in the code as annotations (this isn't compatible with Python 2)
- adding the types as type comments (compatible with Python 2 and 3)

### LINKED ISSUE #365: [fyi] stubs for freezegun were submitted to typeshed
Type stubs for this library were submitted to typeshed in https://github.com/python/typeshed/pull/4425

You don't need to take any action, but:
a) If you wish to include type stubs as part of your package, we're happy to transfer them to this repo (or potentially aid with the addition of inline types)
b) If you want us to remove the stubs from typeshed, we will!

### PR DESCRIPTION
**Pull request by staticdev**
Closes #318
Closes #319
Closes #365

### CODE REVIEW

**Comment by staticdev** [comment]
@boxed I created this new one that is not draft instead of #319.

**Comment by staticdev** [comment]
@boxed @pganssle could you check this please?

**Comment by boxed** [comment]
Thanks!

**Comment by staticdev** [comment]
@boxed could you please release a new version with this change?

**Comment by gitpushdashf** [comment]
> @boxed could you please release a new version with this change?

I believe this is already in 1.2.1.

**Comment by staticdev** [comment]
@gitpushdashf you are right. Typing definitions are still problematic.
I created PRs #454 and #455 to address that.

**Comment by staticdev** [comment]
@spulec could you add me as maintainer? I could be of some help to cleanup the issues/PRs.

**Pull request merged**
