### PR TITLE
Update setup.py to reflect the nose to pytest move

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by koobs** [comment]
Might be worth adding the rest of development deps to extras_require and have tox install freezegun[dev]

Looks like there a couple of other nose breadcrumbs laying about too:

tox.ini:   [testenv] commands = make test NOSE_ARGS="{posargs}"
Makefile: tdaemon: tdaemon -t nose ./tests/ --custom-args="--with-growl"

**Comment by boxed** [comment]
@koobs sounds good! But maybe a separate pr?

**Comment by koobs** [comment]
@boxed Sure (for extras_require), but the other nose->pytest changes are probably worth doing here as they are all part of the same logical change proposal

**Comment by pganssle** [comment]
`tests_require` is deprecated and appears to have been removed from the main branch of the repo now, so I think this PR can be closed as obsolete.

**Comment by boxed** [comment]
Thanks

**Pull request closed without merging**
