### PR TITLE
Allow to configure default ignore list

### PR DESCRIPTION
**Pull request by lukaszb**
Backstory: some tests started to fail with some cryptic errors. Ended up it started happening after adding `tenserflow` package. Now we need to somehow remember to always ignore it or create wrapper around `freeze_time` calls.

With ability to configure default ignore list it would be much simpler.

Let me know if this makes sense.

### CODE REVIEW

**Comment by boxed** [comment]
I like it!

How about changing

```python
def configure(default_ignore=None):
    settings.default_ignore = default_ignore
```

to something like:


```python
def configure(default_ignore=None, add_ignores=None):
    assert default_ignore is None or add_ignores is None, "You can only override the full list, or add to the default. Both at the same time doesn't make sense"
    if default_ignore is not None:
        settings.default_ignore = default_ignore
    else:
        settings.default_ignore = DEFAULT_IGNORE + add_ignores
```

Writing this I think some renames would be nice too:

DEFAULT_IGNORE -> DEFAULT_IGNORE_LIST

default_ignore -> default_ignore_list
add_ignores -> add_to_ignore_list

**Comment by lukaszb** [comment]
@boxed makes sense, done. I've swapped `assert` to custom exception as assertions might be omitted (i.e. if run with `python -O`)

**Comment by boxed** [comment]
Nice.

I don't agree with the custom exception though. Assertions can be omitted sure, but that's pretty pathological since this library is primary for tests and running tests with asserts turned off defeats the purpose :)

**Comment by lukaszb** [comment]
Right, good point :) Still I believe custom exception is more elegant. But that's my opinion.

Anyway, wanna me to change exception to assertion? Any other changes or it looks like something that can be accepted?

**Comment by boxed** [comment]
Yea, let's not argue over irrelevant details. MERGE! :)

**Comment by remik** [comment]
Hi @boxed 
Could you release it?

**Comment by boxed** [comment]
I can't unfortunately, I don't have access on pypi. @spulec must either give me permission or make a release.

**Comment by spulec** [comment]
@boxed sorry for my recent absence. I've added you on PyPI. Feel free to make a release as helpful.

**Comment by remik** [comment]
Great so @boxed all for you :)

**Comment by boxed** [comment]
Published a new release!

**Comment by remik** [comment]
Great. Thank you!

**Pull request merged**
