### PR TITLE
[cleanup] Fix CI by removing maya for pypy3 test and some various cleanup

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by boxed** [comment]
I don't think we should drop pypy...

**Comment by Djailla** [comment]
It fails for testing, not to deploy.

About CI, any though migrating to github actions ?

**Comment by boxed** [comment]
This commit does remove pypy from setup.py and I don't trust support if we can't get it to work in CI. This isn't good imo.

**Comment by boxed** [comment]
As for github actions: I don't really care. I have more experience with Travis.

**Comment by Djailla** [comment]
Hello @boxed I did some changes to the PR if you want to check

**Comment by boxed** [comment]
Thanks for the fixes!

**Pull request merged**
