### PR TITLE
Fix as_kwarg type annotations

### PR DESCRIPTION
**Pull request by joey-rescale**
This fixes mypy errors and is probably also relevant to #439.

### CODE REVIEW

**Comment by boxed** [comment]
Why str? It seems to me like it should be bool.

**Comment by joey-rescale** [comment]
https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L785
It's an index into a dict, hence str. (Unlike `as_arg` which is a bool)
Also see the default value on line 796 which is `''`.

**Comment by boxed** [comment]
Ah, my bad. Thanks.

**Comment by joey-rescale** [comment]
Thanks! There's no rush on my end (I'm using `type: ignore`), but for my own knowledge, what's the release cadence for this package?

**Comment by boxed** [comment]
Totally random and very seldom.

**Comment by joey-rescale** [comment]
Fair enough, thanks!

JOEY MARIANER

Senior Backend Engineer

Rescale ▪ High Performance Computing Built for the Cloud ▪ rescale.com
<http://www.rescale.com>

33 New Montgomery St. ▪ San Francisco, CA 94105

***@***.***

**Pull request merged**
